# Generated by Django 5.1.4 on 2025-01-19 20:55

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat_', unique=True)),
                ('title', models.CharField(default='Título de la categoría', max_length=100, verbose_name='titulo')),
                ('image', models.ImageField(default='category.jpg', upload_to='category', verbose_name='imagen_categoria')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='dirección')),
                ('status', models.BooleanField(default=False, verbose_name='estado')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='estado')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='país')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='código postal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=4, max_length=20, prefix='cart_', unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='precio')),
                ('paid_status', models.BooleanField(default=False, verbose_name='pago_seguimiento')),
                ('product_status', models.CharField(choices=[('Activo', 'activo'), ('Active', 'active'), ('inactive', 'inactivo'), ('Inactive', 'Inactivo'), ('processing', 'procesando'), ('Processing', 'Procesando'), ('delivered', 'entregado'), ('Delivered', 'Entregado')], default='procesando', max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido_carrito',
                'verbose_name_plural': 'pedidos_carrito',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoce_number', models.CharField(default='Número de factura', max_length=200, verbose_name='número_factura')),
                ('product_status', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='precio')),
                ('total', models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder')),
            ],
            options={
                'verbose_name': 'pedido_carrito_item',
                'verbose_name_plural': 'pedidos_carrito_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='pro_', unique=True)),
                ('product_title', models.CharField(default='Título del producto', max_length=100, verbose_name='titulo_producto')),
                ('image', models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path, verbose_name='imagen_producto')),
                ('description', models.TextField(default='Descripción del producto', max_length=255, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='precio')),
                ('old_price', models.DecimalField(decimal_places=2, default=2.99, max_digits=10, verbose_name='precio_anterior')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='especificaciones')),
                ('in_stock', models.BooleanField(default=True, verbose_name='en_stock')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('product_status', models.CharField(choices=[('draft', 'borrador'), ('Draft', 'Borrador'), ('disabled', 'deshabiltado'), ('Disabled', 'Deshabilitado'), ('rejected', 'rechazado'), ('Rejected', 'Rechazado'), ('approved', 'aprobado'), ('Approved', 'Aprobado'), ('pending', 'pendiente'), ('Pending', 'Pendiente'), ('published', 'publicado'), ('Published', 'Publicado'), ('unpublished', 'no publicado'), ('Unpublished', 'No publicado'), ('in_review', 'en_revisión'), ('In_Review', 'En_Revisión')], default='en_revisión', max_length=20)),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=20, prefix='sku_', unique=True)),
                ('digital', models.BooleanField(default=False, verbose_name='digital')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tags')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product.jpg', upload_to='product-images', verbose_name='imagen_producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name': 'imagen_producto',
                'verbose_name_plural': 'imagenes_productos',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default='★★★☆☆')),
                ('review', models.TextField(verbose_name='revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisión_producto',
                'verbose_name_plural': 'revisiones_producto',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven_', unique=True)),
                ('vendor_name', models.CharField(default='Nombre del proveedor', max_length=100, verbose_name='nombre_proveedor')),
                ('logo', models.ImageField(default='proveedor.jpg', upload_to=core.models.user_directory_path, verbose_name='logo')),
                ('description', models.TextField(blank=True, default='Descripción del proveedor', null=True, verbose_name='descripción')),
                ('address', models.CharField(default='Calle 6 sur # 71d - 77', max_length=255, verbose_name='dirección')),
                ('contact', models.CharField(default='+57 (123) 4567890', max_length=100, verbose_name='contacto')),
                ('chat_resp_time', models.CharField(default='En menos de 24 horas', max_length=100, verbose_name='tiempo de respuesta')),
                ('shipping_time', models.CharField(default='De 3 a 5 días hábiles', max_length=100, verbose_name='tiempo de envío')),
                ('shipping_policy', models.TextField(blank=True, null=True, verbose_name='política de envío')),
                ('authentic_rating', models.FloatField(default=4.5, verbose_name='calificación auténtica')),
                ('days_return', models.IntegerField(default=30, verbose_name='días de devolución')),
                ('warranty', models.CharField(default='Garantía de 6 meses', max_length=100, verbose_name='garantía')),
                ('website', models.URLField(default='https://www.example.com', max_length=100, verbose_name='sitio_web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista_deseos',
                'verbose_name_plural': 'listas_deseos',
            },
        ),
    ]
