# Generated by Django 5.1.4 on 2025-01-21 04:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'Pedido Carrito', 'verbose_name_plural': 'Pedidos Carrito'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name': 'Item Pedido Carrito_', 'verbose_name_plural': 'Items Pedidos carrito'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Producto En Revisión', 'verbose_name_plural': 'Producto En Revision'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Lista de Deseos'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=False, verbose_name='Seguimiento de Pago'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='invoce_number',
            field=models.CharField(default='Número de factura', max_length=200, verbose_name='Número Factura'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descripción del producto', max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, verbose_name='Digital'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='En Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=10, verbose_name='Precio Anterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(default='Título del producto', max_length=100, verbose_name='Titulo Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images', verbose_name='Imagen Producto'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='Nombre del proveedor', max_length=100, verbose_name='Empresa'),
        ),
    ]
