# Generated by Django 5.1.4 on 2025-01-21 05:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_options_alter_cartorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'Pedido en  Carrito', 'verbose_name_plural': 'Pedidos en Carrito'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Imagen del producto', 'verbose_name_plural': 'Imagenes del producto'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='Calle 6 sur # 71d - 77', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.FloatField(default=4.5, verbose_name='Calificación auténtica'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(default='En menos de 24 horas', max_length=100, verbose_name='Tiempo de respuesta'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='+57 (123) 4567890', max_length=100, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.IntegerField(default=30, verbose_name='Días de devolución'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='Descripción del proveedor', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default='proveedor.jpg', upload_to=core.models.user_directory_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Política de envío'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_time',
            field=models.CharField(default='De 3 a 5 días hábiles', max_length=100, verbose_name='Tiempo de envío'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='Nombre del proveedor', max_length=100, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty',
            field=models.CharField(default='Garantía de 6 meses', max_length=100, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(default='https://www.example.com', max_length=100, verbose_name='Sitio web'),
        ),
    ]
