# Generated by Django 5.1.4 on 2025-01-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartorder_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Disabled', 'Deshabilitado'), ('Rejected', 'Rechazado'), ('Approved', 'Aprobado'), ('Pending', 'Pendiente'), ('Published', 'Publicado'), ('Unpublished', 'No publicado'), ('InReview', 'En Revisión')], default='En revisión', max_length=20, verbose_name='Estado Del Producto'),
        ),
    ]
