# Generated by Django 5.1.4 on 2025-01-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
