# Generated by Django 5.1.4 on 2025-01-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Disabled', 'Deshabilitado'), ('Rejected', 'Rechazado'), ('Approved', 'Aprobado'), ('Pending', 'Pendiente'), ('Published', 'Publicado'), ('Unpublished', 'No publicado'), ('InReview', 'En Revisión')], default='En revisión', max_length=20, verbose_name='Estado de Categoria'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Disabled', 'Deshabilitado'), ('Rejected', 'Rechazado'), ('Approved', 'Aprobado'), ('Pending', 'Pendiente'), ('Published', 'Publicado'), ('Unpublished', 'No publicado'), ('InReview', 'En Revisión')], default='En revisión', max_length=20, verbose_name='Estado de Vendedor'),
        ),
    ]
