# Generated by Django 5.1.4 on 2025-01-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_category_status_vendor_vendor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='vendor', to='core.vendor'),
        ),
    ]
