# Generated by Django 5.1.4 on 2025-01-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
    ]
