# Generated by Django 5.1.4 on 2025-01-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_image_productimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='Descripción Larga del producto', max_length=255, verbose_name='Descripción Larga'),
        ),
    ]
