# Generated by Django 5.1.4 on 2025-01-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='Descripción Larga del producto', verbose_name='Descripción Larga'),
        ),
    ]
