# Generated by Django 5.1.4 on 2025-01-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del color')),
                ('hex_code', models.CharField(help_text='Ej: #FF0000', max_length=7, verbose_name='Código_Hex')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='colores',
            field=models.ManyToManyField(blank=True, to='core.color', verbose_name='colores disponibles'),
        ),
    ]
