# Generated by Django 5.1.4 on 2025-01-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_color_product_colores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edad',
            field=models.CharField(choices=[('1', '0-6 Meses'), ('2', '6-12 Meses'), ('3', '1-2 Años'), ('4', '2-3 Años'), ('5', '3-6 Años'), ('6', '6-9 Años'), ('7', '9-12 Años'), ('7', '12+ Años')], default='1', max_length=20, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación'),
        ),
    ]
