# Generated by Django 5.1.4 on 2025-01-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_edad_product_mfd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_description',
        ),
    ]
