# Generated by Django 5.1.4 on 2025-01-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre de usuario'),
        ),
    ]
