# Generated by Django 5.1.4 on 2025-01-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
