# Generated by Django 5.1.4 on 2025-01-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='default.png', max_length=255, verbose_name='nombre de usuario'),
        ),
    ]
